site_name: Vick's Wiki
theme:
  name: material    
nav:
  - 首页: index.md
  - Graph:
    - DSU: Note/Graph/DSU/DSU.md
    - Topsort: Note/Graph/Topsort/Topsort.md
  - 指南: guides/install.md
  - 关于: about.md

plugins:           
  - search        

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # 启用通用数学模式

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # MathJax 3