site_name: Vick's Wiki
theme:
  name: material    

  font:
    text: Geogia
  icon:
    logo: material/pen
  features:
    - header.autohide
    - navigation.top
    - navigation.tabs
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 首页: index.md
  - Basic:
    - Priority of operations: Note/Basic/Priority of operations.md
  - Data Structure:
    - Queue: about.md
    - Stack: about.md
  - DP: about.md
  - Math: about.md
  - Graph:
    - Types of Graph: 
      - DAG: Note/Graph/Types of Graph/DAG.md
    - DSU: Note/Graph/DSU.md
    - Topological sorting: Note/Graph/Topological sorting.md
    - Meet in the middle: Note/Graph/Meet in the middle.md
    - Trie: Note/Graph/Trie.md
  - 指南: guides/install.md
  - 关于: about.md

plugins:           
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # 启用通用数学模式

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # MathJax 3